apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: tpmg-tdm
  name: tpmg-tdm
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: tpmg-tdm
status:
  loadBalancer: {}
