apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: tpmg-ml
  name: tpmg-ml
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    run: tpmg-ml
status:
  loadBalancer: {}
